version: '2'

services:
  web-dev:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
      - /code/node_modules
    command: npm run debug
