version: '2'

services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./model/database.sql:/docker-entrypoint-initdb.d/1.ddl-schema.sql
volumes: 
  postgres-data: