version: '2'

services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /code/node_modules
  db:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./model/database.sql:/docker-entrypoint-initdb.d/1.ddl-schema.sql
volumes: 
  postgres-data: