version: '2'

services:
  web-dev:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
      - /code/node_modules
    command: npm run debug
  db:
    restart: always
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./model/database.sql:/docker-entrypoint-initdb.d/1.ddl-schema.sql
volumes: 
  postgres-data-dev: